image: javiersantos/android-ci:27.0.2

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/wrapper
     - .gradle/caches

stages:
  - build
  - package
  - test

build:
  stage: build
  script:
    - ./gradlew --no-daemon build
  artifacts:
    paths:
      - build/outputs/
      - build/libs/
      - build/poms/

install:
  stage: package
  script:
    - ./gradlew --no-daemon --stacktrace install
  artifacts:
    paths:
      - build/outputs/
      - build/libs/
      - build/poms/

#unitTests:
#  stage: test
#  script:
#    - ./gradlew --no-daemon test

#functionalTests:
#  stage: test
#  script:
#    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
#    - chmod +x android-wait-for-emulator
#    - echo y | android-sdk/tools/android --silent update sdk --no-ui --all --filter sys-img-x86-google_apis-${ANDROID_COMPILE_SDK}
#    - echo no | android-sdk/tools/android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
#    - android-sdk/tools/emulator64-x86 -avd test -no-window -no-audio &
#    - ./android-wait-for-emulator
#    - adb shell input keyevent 82
#    - ./gradlew --no-daemon cAT
#  artifacts:
#    paths:
#    - app/build/reports/androidTests/
