sudo: false
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - '.+'

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install:
#  - mkdir "$ANDROID_HOME/licenses" || true
#  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#  #- chmod +x ./sdkmanager-accept-licenses.sh
#  - chmod +x ./gradlew
#  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
#  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --licenses
#  #- ./sdkmanager-accept-licenses.sh
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build

after_failure:
  - cat $TRAVIS_BUILD_DIR/lint-results-debug.xml

after_success:
  - ./gradlew test jacocoTestReport coveralls
