sudo: false
language: android

jdk:
  - oraclejdk8

android:
  components:
    - android-27
    - build-tools-27.0.2
    - platform-tools
    - add-on
    - extra

# buildToolsVersion = '27.0.2'

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - '.+'

branches:
  except:
    - gh-pages

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
#  - mkdir "$ANDROID_HOME/licenses" || true
#  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#  #- chmod +x ./sdkmanager-accept-licenses.sh
#  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
#  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --licenses
  - yes | sdkmanager "platforms;android-27"
  - chmod +x ./gradlew

script:
  - ./gradlew --no-daemon build

after_failure:
  - cat $TRAVIS_BUILD_DIR/lint-results-debug.xml

after_success:
  - ./gradlew test jacocoTestReport coveralls
